name: test-https
on:
  push:
    branches:
      - main
jobs:
  test-https:
    name: test-https
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    concurrency:
      group: test-https
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.14
      - run: bun install
      - run: USE_HTTPS=true bun run test
