name: test
on:
  push:
    branches:
      - main
jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    concurrency:
      group: test
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.14
      - run: bun install
      - run: bun run test
